project_id = "backend-stack-template"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.migrations]
enabled = true
schema_paths = []

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.buckets.uploads]
public = false
file_size_limit = "50MiB"
